apiVersion: apps/v1
kind: Deployment
metadata:
  name: type-10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: type-10
  template:
    metadata:
      labels:
        app: type-10
    spec:
      containers:
        - name: type-10
          image: docker.io/timattt/type-10:latest
          imagePullPolicy: Always
          env:
            - name: TYPE10_RABBIT_HOST
              value: rabbitmq.default.svc.cluster.local
            - name: TYPE10_RABBIT_PORT
              value: "15672"
            - name: TYPE10_RABBIT_USERNAME
              value: "rabbit"
            - name: TYPE10_RABBIT_PASSWORD
              value: "rabbit"
            - name: TYPE10_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: type-10-mail-creds
                  key: username
            - name: TYPE10_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: type-10-mail-creds
                  key: password
